version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    labels:
      - "package management"

  - package-ecosystem: "pip"
    directory: "/Python"
    schedule:
      interval: "weekly"
    labels:
      - "lang: Python"

  - package-ecosystem: "gradle"
    directory: "/Java"
    schedule:
      interval: "weekly"
    labels:
      - "lang: Java"