# ToDo: Add support for Go and other languages

matrix:
  include:
    - language: java
      jdk:
        - openjdk8
        - oraclejdk8
        - openjdk9
        - oraclejdk9
      before_script:
        - cd Java
      script:
        - javac Example.java

notifications:
  email: false
  irc:
    - "irc.dilley.me#sysadmininkudzu"
    - "chat.freenode.net#minestat"
    - "irc.oftc.net#minestat"
