# ToDo: Add support for Go and other languages

matrix:
  include:
    - language: java
      jdk:
        - oraclejdk7
        - openjdk7
        - oraclejdk8
      before_script:
        - cd Java
      script:
        - javac Example.java

notifications:
  email: false
  irc:
    - "irc.dilley.me#sysadmininkudzu"
    - "chat.freenode.net#minestat"
    - "irc.oftc.net#minestat"
