name: Publish Maven Package

on:
  workflow_dispatch:

jobs:
  publish-maven:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Java/

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'

      # TODO: Replace! This action is archived since Jan 2023: https://github.com/samuelmeuli/action-maven-publish
      - name: Publish Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          nexus_username: ${{ secrets.MAVEN_USER }}
          nexus_password: ${{ secrets.MAVEN_TOKEN }}
          directory: Java/
          maven_args: "-DskipTests"
